query UserPositions(
  $address: String!
  $startTimestamp: Int!
  $endTimestamp: Int!
) {
  userByAddress(address: $address) {
    address
    marketPositions {
      market {
        ...MarketCore
        historicalState {
          borrowApy(
            options: {
              startTimestamp: $startTimestamp
              endTimestamp: $endTimestamp
              interval: DAY
            }
          ) {
            x
            y
          }
        }
      }

      borrowAssets
      borrowShares
      borrowAssetsUsd
      collateral
      collateralUsd
      healthFactor
    }
  }
}

fragment MarketCore on Market {
  uniqueKey
  loanAsset {
    id
    address
    decimals
    name
    symbol
  }
  collateralAsset {
    id
    address
    decimals
    name
    symbol
  }
  state {
    utilization
    borrowApy
    netBorrowApy
  }
}
