query UserPositions($address: String!) {
  userByAddress(address: $address) {
    address
    marketPositions {
      market {
        uniqueKey
        loanAsset {
          id
          address
          decimals
          name
          symbol
        }
        collateralAsset {
          id
          address
          decimals
          name
          symbol
        }
        state {
          utilization
          borrowApy
          netBorrowApy
        }
      }

      borrowAssets
      borrowShares
      borrowAssetsUsd
      collateral
      collateralUsd
      healthFactor
    }
  }
}
